import streamlit as st
def translate(text):
    translations = {
        "English": {
            "Language Selection": "Language Selection",
            "Choose your language:": "Choose your language:",
            "title": "EmoBot: AI-Powered for Mental Health Support",
            "run": "Run",
            "stopped": "Stopped",
            "your_sentence": "Your Sentence!",
            "final_result": "Final Result",
            "show": "Show",
            "emotion": "Emotion",
            "probability": "Probability",
            "anger": "Angry",
            "disgust": "Disgust",
            "fear": "Fear",
            "joy": "Joy",
            "happy": "Happy",
            "sadness": "Sad",
            "surprise": "Surprise",
            "neutral": "Neutral",
            "love": "Love",
            "Angry": "Angry",
            "Disgust": "Disgust",
            "Fear": "Fear",
            "Happy": "Happy",
            "Sad": "Sad",
            "Surprise": "Surprise",
            "Neutral": "Neutral",
            "You want to meet a doctor?":"You want to meet a doctor?",
            "Click here!": "Click here!"
        },
        "Vietnamese": {
            "Language Selection": "Lựa chọn ngôn ngữ",
            "Choose your language:": "Chọn ngôn ngữ của bạn",
            "title": "EmoBot: AI-Powered trong hỗ trợ sức khỏe tâm thần",
            "run": "Chạy",
            "stopped": "Dừng lại",
            "your_sentence": "Câu của bạn!",
            "final_result": "Kết quả cuối cùng",
            "show": "Hiển thị",
            "emotion": "Cảm xúc",
            "probability": "Xác suất",
            "anger": "Giận dữ",
            "joy": "Vui Sướng",
            "disgust": "Ghê tởm",
            "fear": "Sợ hãi",
            "happy": "Hạnh phúc",
            "sadness": "Buồn bã",
            "surprise": "Ngạc nhiên",
            "neutral": "Trung lập",
            "love": "Yêu",
            "Angry":"Giận dữ",
            "Disgust":"Ghê tởm",
            "Fear":"Sợ hãi",
            "Happy":"Hạnh phúc",
            "Sad":"Buồn bã",
            "Surprise":"Ngạc nhiên",
            "Neutral":"Bình thường",
            "You want to meet a doctor?":"Bạn muốn gặp bác sĩ?",
            "Click here!": "Bấm vào đây!"
        }

    }
    return translations[st.session_state.language].get(text, text)